### ISSUE TITLE
zwave thermostat issue

### ISSUE THREAD

**Issue by JonGilmore** [shbatm/home-assistant#1]
**Component/platform:**
custom isy994 component

**Description of problem:**
attempting to add a zwave thermostat from ISY into HASS via the custom component.

**Traceback (if applicable):**
```
2019-05-12 19:31:37 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 256, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/home/homeassistant/.homeassistant/custom_components/isy994/__init__.py", line 484, in device_state_attributes
    for name, val in self._node.aux_properties.items():
AttributeError: 'list' object has no attribute 'items'
```

**Additional information:**
Here’s what the _node.aux_properties contains:
```
[{'uom': ['67'], 'id': 'CLIMD', 'prec': '0', 'value': 1}, 
{'uom': ['17'], 'id': 'CLISPC', 'prec': '0', 'value': 77}, 
{'uom': ['17'], 'id': 'CLISPH', 'prec': '0', 'value': 70}]
```

additional debug logging will be posted below.

**Comment by jon102034050** [comment]
```2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="8" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="3" area="1" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="9" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="2" area="1" val="1" /></eventInfo></Event>
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.isy994
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="10" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="1" area="2" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 DEBUG (Thread-8) [custom_components.isy994.sensor] Loading main thermostat
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="11" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="3" area="2" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 INFO (Thread-16) [homeassistant.loader] Loaded group from homeassistant.components.group
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="12" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="2" area="2" val="1" /></eventInfo></Event>
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.components.climate] Setting up climate.isy994
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="13" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="1" area="3" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="14" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="3" area="3" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.isy994
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="15" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="2" area="3" val="1" /></eventInfo></Event>
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.setup] Setting up group
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="16" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="1" area="4" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.0 seconds.
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="17" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="3" area="4" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 256, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/home/homeassistant/.homeassistant/custom_components/isy994/__init__.py", line 484, in device_state_attributes
    for name, val in self._node.aux_properties.items():
AttributeError: 'list' object has no attribute 'items'
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="18" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="2" area="4" val="1" /></eventInfo></Event>
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="19" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="1" area="5" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="20" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="3" area="5" val="0" /></eventInfo></Event>
2019-05-12 19:31:37 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="21" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="2" area="5" val="1" /></eventInfo></Event>
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.setup] Setting up light
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.setup] Setting up fan
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.setup] Setup of domain fan took 0.0 seconds.
2019-05-12 19:31:37 INFO (MainThread) [homeassistant.setup] Setting up lock
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.setup] Setup of domain lock took 0.0 seconds.
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.setup] Setting up cover
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.setup] Setup of domain cover took 0.0 seconds.
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.setup] Setting up switch
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.setup] Setup of domain switch took 0.0 seconds.
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.setup] Setup of domain light took 0.1 seconds.
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.components.fan] Setting up fan.isy994
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.components.lock] Setting up lock.isy994
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.components.cover] Setting up cover.isy994
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.components.switch] Setting up switch.isy994
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.components.light] Setting up light.isy994
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 3.85s
2019-05-12 19:31:38 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2019-05-12 19:31:40 INFO (MainThread) [homeassistant.core] Timer:starting
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="22" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="1" area="6" val="0" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="23" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="3" area="6" val="0" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="24" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="2" area="6" val="1" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="25" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="1" area="7" val="0" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="26" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="3" area="7" val="0" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="27" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="2" area="7" val="1" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="28" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="1" area="8" val="0" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="29" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="3" area="8" val="0" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="30" sid="uuid:32"><control>_19</control><action>2</action><node></node><eventInfo><ae type="2" area="8" val="1" /></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="31" sid="uuid:32"><control>ST</control><action uom="17" prec="0">73</action><node>ZW002_1</node><eventInfo></eventInfo><fmtAct>73°F</fmtAct></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Updated Node: ZW002_1
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Node Control Event: ZW002_1 ST 73
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="32" sid="uuid:32"><control>CLIFRS</control><action uom="80" prec="0">0</action><node>ZW002_1</node><eventInfo></eventInfo><fmtAct>Off</fmtAct></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Node Control Event: ZW002_1 CLIFRS 0
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="33" sid="uuid:32"><control>CLIFS</control><action uom="68" prec="0">0</action><node>ZW002_1</node><eventInfo></eventInfo><fmtAct>Auto</fmtAct></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Node Control Event: ZW002_1 CLIFS 0
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="34" sid="uuid:32"><control>CLIFSO</control><action uom="81" prec="0">0</action><node>ZW002_1</node><eventInfo></eventInfo><fmtAct>No Override</fmtAct></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Node Control Event: ZW002_1 CLIFSO 0
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="35" sid="uuid:32"><control>CLISPC</control><action uom="17" prec="0">77</action><node>ZW002_1</node><eventInfo></eventInfo><fmtAct>77°F</fmtAct></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Node Control Event: ZW002_1 CLISPC 77
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="36" sid="uuid:32"><control>CLISPH</control><action uom="17" prec="0">69</action><node>ZW002_1</node><eventInfo></eventInfo><fmtAct>69°F</fmtAct></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Node Control Event: ZW002_1 CLISPH 69
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="37" sid="uuid:32"><control>CLIHCS</control><action uom="66" prec="0">0</action><node>ZW002_1</node><eventInfo></eventInfo><fmtAct>Idle</fmtAct></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Node Control Event: ZW002_1 CLIHCS 0
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="38" sid="uuid:32"><control>CLIMD</control><action uom="67" prec="0">1</action><node>ZW002_1</node><eventInfo></eventInfo><fmtAct>Heat</fmtAct></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Node Control Event: ZW002_1 CLIMD 1
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="39" sid="uuid:32"><control>_4</control><action>5</action><node></node><eventInfo><status>0</status></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="40" sid="uuid:32"><control>_4</control><action>6</action><node></node><eventInfo><status>1</status></eventInfo></Event>
2019-05-12 19:31:46 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="41" sid="uuid:32"><control>_22</control><action>1</action><node></node><eventInfo><totalCostToday>0.000000</totalCostToday><totalCostPeriod>0.000000</totalCostPeriod><totalUsagePeriod>0.000000</totalUsagePeriod><cycleEndTime>2019/05/12  1:31:38 PM</cycleEndTime></eventInfo></Event>
2019-05-12 19:32:11 DEBUG (Thread-22) [custom_components.isy994] ISY Update Received:
<?xml version="1.0"?><Event seqnum="42" sid="uuid:32"><control>_0</control><action>120</action><node></node><eventInfo></eventInfo></Event>
2019-05-12 19:32:11 DEBUG (Thread-22) [custom_components.isy994] ISY HEARTBEAT: 2019-05-12T19:32:11.374905
```

**Comment by jon102034050** [comment]
I think I'm onto something here.... Based upon that error I'm seeing, and the data, it's having an issue with that data coming back because I think it's a list of dicts, and your code assumes it is only going to get a dict back. I'm sorta a python noob, but this is my best guess at the moment.

**Comment by jon102034050** [comment]
Check this gist out: https://gist.github.com/randellhodges/ffbea36ac034edd20e45a5591a7ea179

If I make the following change, I can at least see the thermostat show up in HASS: 

```    def device_state_attributes(self) -> Dict:
        """Get the state attributes for the device."""
        attr = {}
        if hasattr(self._node, 'aux_properties'):
            for prop in self._node.aux_properties:
                attr[prop.get('id')] = '{} {}'.format(prop.get('value'), prop.get('uom'))
        return attr
```

**Comment by jon102034050** [comment]
after digging deeper, looks like this _may_ be related to an upstream issue with PyISY: https://github.com/automicus/PyISY/pull/43

**Comment by shbatm** [comment]
There is an issue with the upstream module, (actually several, which is why I forked it and it's using a custom version) but it's interesting you're still seeing that error because that code shouldn't be getting called. It should be overloaded by the code in `isy994/climate.py` at [Line 288](https://github.com/shbatm/home-assistant/blob/186f7ecdb9e9c8a7d87c8c141f42116c1ec92c0f/homeassistant/components/isy994/climate.py#L288).  Like I said, I saw that error, but it went away when I corrected the climate code... I'll need to dig in a little more, but it'll be about 2 weeks before I can really sit down and look at it.

**Comment by shbatm** [comment]
What version of Hass are you running?

**Comment by jon102034050** [comment]
Right on - I noticed that your manifest called the PyISY beta in PyPi, and I'm _pretty_ sure the custom component is downloading and using that, which is why Im a little confused I'm seeing this error as well.... My HASS version is 0.92.2
